### ISSUE TITLE
Use duckuments package

### ISSUE THREAD

**Issue by AlexDaniel** [TUT-ASI/thesis-template#6]
We already use `blindtext` for some examples, it probably makes sense to also use `duckuments` for images.

Some nice (possibly unrelated) examples [here](https://tex.stackexchange.com/questions/419751/getting-ducks-in-example-images).

Reto++ for the idea.

**Comment by retogaeh** [comment]
Added an example with a duck stub aka example-image-duck to visualise multiple figures with minipages as well as subfigures. Also added a footnote inside of caption.

**Comment by AlexDaniel** [comment]
@retogaeh just merged your branch and had a good laugh when looked at the rendered document. This is awesome.
